### ISSUE TITLE
Is this some kind of interactive tutorial Using DRAKON-C?

### ISSUE THREAD

**Issue by vasili111** [ker2x/drakon-scheme#1]
Is this some kind of interactive tutorial for Scheme using DRAKON-C? I did not find any kind of information about it at: http://peter.michaux.ca/articles/scheme-from-scratch-introduction

**Comment by ker2x** [comment]
No it's not. I was trying to follow this tutorial using drakon instead of good old regular C. But it wasn't a good idea, i never finished it :)

**Comment by vasili111** [comment]
> No it's not. I was trying to follow this tutorial using drakon instead of good old regular C. But it wasn't a good idea, i never finished it :)

It was not good idea becouse of DRAKON or DRAKON Editor or it was other kind of problem?
If problem was in DRAKON or DRAKON Editor then what kind of problem it was?

**Comment by ker2x** [comment]
Because for each step of the tutorial you have to redraw most of the drakon graphs and it really is awful and time consuming.
You don't develop in DRAKON the same way you develop in C, and this tutorial is for C :)

**Comment by vasili111** [comment]
Thank you for your answers :)
